baseURL = 'https://dogukanteber.github.io/'
languageCode = 'en-us'
title = "Doğukan's Blog"
theme = "hugo-ink"
publishDir = "docs"

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-PKHMQYVY49"

# Optional 64x64 avatar image.
avatar = "https://cdn.openai.com/dall-e-2/demos/text2im/astronaut/basketball/minimalist/0.jpg"
# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

featherIconsCDN = true

mode = "auto" # "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[params]
subtitle = "About programming, computing and math"

[[params.social]]
icon = "linkedin"
icon_pack = "fa"
url = "https://linkedin.com/in/dogukanteber"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/dogukanteber"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[pagination]
pagerSize = 10

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Open Source Contributions"
url = "/open_source"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

[taxonomies]
tag = "tags"


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
